### ISSUE TITLE
Namespace conflict with the example

### ISSUE THREAD

**Issue by ndench** [DATA-DOG/DataDogAuditBundle#13]
This is an awesome bundle! Only issue I'm having is that my project bundle is called `AppBundle` and so is the one in the example. Which means that my `Project` and `User` entities get namespace conflicts with the example.

It doesn't actually cause any errors, but it does make PhpStorm complain that there are multiple definities for the classes.

Is there a way I can install the bundle without the example?

**Comment by l3pp4rd** [comment]
thanks, well, this is an example app, copy the source code or rename it. it is built to demo it.

**Comment by ndench** [comment]
Ok fair enough, I thought that might be the case. Thanks for the quick reply.
