### ISSUE TITLE
Setting the blamed user from a console command

### ISSUE THREAD

**Issue by ndench** [DATA-DOG/DataDogAuditBundle#17]
I've recently run into a problem, we need to do a database update which requires some data migrations. I've written a symfony command to do the data migrations but it creates an AuditLog with a `null` blame id. I was able to get around the problem my hacking around it and simulating a login like this: https://stackoverflow.com/questions/22606444/symfony-2-simulate-login-and-security-context-in-console-command

But it would be great if we could programatically set the user that the bundle will use, just like the doctrine extensions blameable: https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/lib/Gedmo/Blameable/BlameableListener.php#L60

I'm happy to contribute this myself if you would like?

**Comment by l3pp4rd** [comment]
Hi, OK that makes sense, open for PR, thanks ;)

**Comment by ndench** [comment]
Hey @l3pp4rd, I finally got around to doing this PR. Sorry it took me so long :stuck_out_tongue:.

Can you take a look and let me know what you think?
