### ISSUE TITLE
Demo is broken - deprecated security.context still being used.

### ISSUE THREAD

**Issue by phryneas** [DATA-DOG/DataDogAuditBundle#22]
When logging in as user Yoda, I get
`You have requested a non-existent service "security.context".`

**Comment by l3pp4rd** [comment]
Hi, could you submit a pull request?

**Comment by phryneas** [comment]
Currently I'm still evaluating if I'm going to use the Bundle at all. 
Honestly, a broken demo might not really pushing me towards it.
But I'm looking at it right now. If it's easy to fix, I might give it a go.

**Comment by phryneas** [comment]
oh well, simple enough. there you go ;)

**Comment by l3pp4rd** [comment]
nice, just create a pull request to this repository, so I can merge it ;) thanks

**Comment by phryneas** [comment]
sorry, I had assumed that github had already done that ^^
