### ISSUE TITLE
Possibility to retrieve ID of entity

### ISSUE THREAD

**Issue by markvdlaan93** [DATA-DOG/DataDogAuditBundle#27]
Is there any possibility to retrieve the ID of the entity which is created/updated/deleted? In the audit_logs table I only see the fields that are inserted in the 'diff'-field but not the ID's such that I can retrieve the particular entity.

**Comment by l3pp4rd** [comment]
Hi, every audit log entry has a relation as [Source](https://github.com/DATA-DOG/DataDogAuditBundle/blob/master/src/DataDog/AuditBundle/Entity/AuditLog.php#L34) which is the logged entity [Association having FK field](https://github.com/DATA-DOG/DataDogAuditBundle/blob/master/src/DataDog/AuditBundle/Entity/Association.php#L38) this **fk** field is the identifier. Though if it is a string field, so if you have large number of logged items and the your ID is integer, you should cast it to String before making a lookup query.

**Comment by l3pp4rd** [comment]
all methods are now protected for extensions
