### ISSUE TITLE
composite key entity exception

### ISSUE THREAD

**Issue by chancegarcia** [DATA-DOG/DataDogAuditBundle#29]
I'm running into an exception thrown in the DataDog\AuditBundle\EventSubscriber\AuditSubscriber class, line 320 when the subscriber tries to record changes to an entity with a composite key.

For now, I'm just adding it to unaudited entities. I'm willing to do modifications to help allow composite key entities to be audit-able.  I'm thinking there may some discussion needed on strategy for handling things. I'll have to look into it more thoroughly when I find a space of time.

**Comment by l3pp4rd** [comment]
Hi, composite keys will not be supported. since we cannot know how many composite key fields there might be. I personally do not use such feature, since it complicates everything even at ORM level. If you do need such a feature, you will have to fork it

**Comment by l3pp4rd** [comment]
no thank you, there is always a work around to achieve certain features, but this library is very small, just copy and use it based on your needs. I have developed highly used open source projects and what makes them bad are bad features, I do not want to deal with that and leaving it to you for your personal experience. there is nothing to consider, there won't be composite key support in this repository.
