### ISSUE TITLE
[Feature Request] Setting blamed user from impersonated user

### ISSUE THREAD

**Issue by stefanogironella** [DATA-DOG/DataDogAuditBundle#56]
Hi,
is there any plan to support setting `blamed user` from `impersonated user` (where applicable)?

Are PR accepted?

Cheers

**Comment by l3pp4rd** [comment]
I have stopped working with php, but you can open a pr, can be accepted

**Comment by stefanogironella** [comment]
Ok, [PR](https://github.com/DATA-DOG/DataDogAuditBundle/pull/59) opened.
