### ISSUE TITLE
Symfony 3

### ISSUE THREAD

**Issue by peschee** [DATA-DOG/DataDogAuditBundle#6]
@l3pp4rd Do you have an idea if there are issues with making this compatible with Symfony 3?

**Comment by l3pp4rd** [comment]
Hi @peschee I think there should not be any issues, only composer file needs to be updated to allow S3 dependency. would you be willing to submit a pull request?

**Comment by peschee** [comment]
There currently are not tests to run, right?

**Comment by l3pp4rd** [comment]
no, only a demo application, which could run on symfony3. the bundle itself is fairly simple since it only implements an event listener.

**Comment by braianj** [comment]
Hi @peschee could you make it work in S3?

**Comment by peschee** [comment]
Hey @braianj we're not really using the bundle, we decided to use https://github.com/simplethings/EntityAuditBundle I merely updated the version numbers in #7 since @l3pp4rd said the bundle SHOULD work in SF3.

**Comment by braianj** [comment]
oh that´s sad. This bundle look promising.

**Comment by l3pp4rd** [comment]
released a tag with an example migrated to symfony3. you could manage that yourself. because the example itself has nothing to do with this bundle. the bundle itself works with both symfony2 and symfony3

**Comment by braianj** [comment]
thank you very much @l3pp4rd . I´ll try again. How can I access to rev data? I managed to save the data, but don´t know how to easy show the changes.

**Comment by braianj** [comment]
Another question: where can I find DataDog\PagerBundle\Pagination;?

**Comment by braianj** [comment]
@l3pp4rd sorry to make this a bit nasty, I could manage to integrate the PagerBundle, AuditBundle and the example itself. Data is filled with info and when I call route app_dev.php/audit, it return me this error

```
An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2 FROM tags t0 WHERE t0.name = ? LIMIT 1' with params ["New"]:

SQLSTATE[42P01]: Undefined table: 7 ERROR: no relationship exist «tags»
LINE 1: SELECT t0.id AS id_1, t0.name AS name_2 FROM tags t0 WHERE t...
^
```
I´m working with postgreSQL if that helps, or you want me to open a new issue?
