### ISSUE TITLE
Can we override or at least change the order of which labels are added? 

### ISSUE THREAD

**Issue by jonrob44** [DATA-DOG/DataDogAuditBundle#61]
We have a bunch of entities with title fields that relate to the title of the user (Mr, Mrs, Miss)

Your switch statement on the subscriber prioritises a title field, which means the title gets saved as Mr rather then our __toString or name fields. 

If you swap __toString to be the upmost priority (as toString is the defacto string representation of the object not any other field) and then check for other fields if its not implemented it would make it more user friendly. Adding a config in the yml for selecting a label field would also be a better implementation.

I have overridden the subscriber, created a new subscriber, inherited and overridden the label function myself for our project, but I think it would be beneficial to swap the order in the repo. I can make a pull request for this if you don't have time. 

Other then that its a great bundle. Thanks.

**Comment by l3pp4rd** [comment]
Hi, there isa method **setLabeler** you can use it to customize the labeling whatever way you want

**Comment by l3pp4rd** [comment]
I will not change the order since the title  is commonly used as a field identifying an object

**Comment by jonrob44** [comment]
I didnt see the setLabeler config, my bad. Easily resolved with that. Sorry for wasting your time. 

Kind Regards.
